#!/bin/bash

# PreFree SpMV Auto-tuning Clean Script
# This script removes all files generated by run_autotuning.sh

echo "================================================"
echo "PreFree SpMV Auto-tuning Clean Script"
echo "================================================"

# Get the project root directory (where this script is located)
PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$PROJECT_ROOT"

echo "Cleaning auto-tuning generated files..."

# 1. Clean build directory
echo "- Cleaning build directory..."
if [ -d "build" ]; then
    rm -rf build/*
    echo "  ✓ Build directory cleaned"
else
    echo "  ! Build directory not found"
fi

# 2. Remove temporary test files
echo "- Removing temporary test files..."
TEMP_FILES_REMOVED=0
for file in src/spmv_kernel/preFreeSpMV_test_*.cu; do
    if [ -f "$file" ]; then
        rm "$file"
        echo "  ✓ Removed: $file"
        TEMP_FILES_REMOVED=$((TEMP_FILES_REMOVED + 1))
    fi
done

if [ $TEMP_FILES_REMOVED -eq 0 ]; then
    echo "  ! No temporary test files found"
fi

# 3. Remove optimized generated file
echo "- Removing generated optimized file..."
OPTIMIZED_FILE="src/spmv_kernel/preFreeSpMV_optimized.cu"
if [ -f "$OPTIMIZED_FILE" ]; then
    rm "$OPTIMIZED_FILE"
    echo "  ✓ Removed: $OPTIMIZED_FILE"
else
    echo "  ! Optimized file not found: $OPTIMIZED_FILE"
fi

# 4. Remove profiling results
echo "- Removing profiling results..."
RESULTS_FILE="scripts/profiling_results.json"
if [ -f "$RESULTS_FILE" ]; then
    rm "$RESULTS_FILE"
    echo "  ✓ Removed: $RESULTS_FILE"
else
    echo "  ! Profiling results file not found: $RESULTS_FILE"
fi

# 5. Restore CMakeLists.txt if it was modified
echo "- Checking CMakeLists.txt..."
if git status --porcelain CMakeLists.txt | grep -q "M"; then
    git restore CMakeLists.txt
    echo "  ✓ CMakeLists.txt restored to original state"
else
    echo "  ✓ CMakeLists.txt is already in original state"
fi

# 6. Clean any CMake cache files in project root
echo "- Cleaning CMake cache files..."
CMAKE_FILES_REMOVED=0
for file in CMakeCache.txt cmake_install.cmake Makefile compile_commands.json; do
    if [ -f "$file" ]; then
        rm "$file"
        echo "  ✓ Removed: $file"
        CMAKE_FILES_REMOVED=$((CMAKE_FILES_REMOVED + 1))
    fi
done

if [ -d "CMakeFiles" ]; then
    rm -rf CMakeFiles
    echo "  ✓ Removed: CMakeFiles directory"
    CMAKE_FILES_REMOVED=$((CMAKE_FILES_REMOVED + 1))
fi

if [ $CMAKE_FILES_REMOVED -eq 0 ]; then
    echo "  ! No CMake cache files found in project root"
fi

echo ""
echo "================================================"
echo "Cleanup completed successfully!"
echo "================================================"
echo ""
echo "The following files/directories have been cleaned:"
echo "  - build/* (all compiled objects and executables)"
echo "  - src/spmv_kernel/preFreeSpMV_test_*.cu (temporary test files)"
echo "  - src/spmv_kernel/preFreeSpMV_optimized.cu (generated optimized code)"
echo "  - scripts/profiling_results.json (profiling results)"
echo "  - CMakeLists.txt (restored to original state)"
echo "  - CMake cache files (if any)"
echo ""
echo "You can now run ./run_autotuning.sh again for a fresh start." 